### ISSUE TITLE
training zephyr-7b

### ISSUE THREAD

**Issue by piyushgit011** [philschmid/llm-sagemaker-sample#10]
hey, @philschmid  i have trained zephyr-7b on qlora but when i am trying to deploy the llm then i am getting a problem :- 
![image](https://github.com/philschmid/llm-sagemaker-sample/assets/96625965/27a3b2d9-f8b0-4924-80e9-1e7b904d7e38)
so, i couldn't create the endpoint.
 can anyone explain why it is happening.
how can i solve this issue?

**Comment by piyushgit011** [comment]
it's saying unsupported model type mistral.

**Comment by piyushgit011** [comment]
this is where the errors starts:-
![image](https://github.com/philschmid/llm-sagemaker-sample/assets/96625965/2816a8e3-b26b-4838-8cb2-871403f70085)

**Comment by piyushgit011** [comment]
now, i am getting this error , after changing gpu. 
![image](https://github.com/philschmid/llm-sagemaker-sample/assets/96625965/b2e0946c-e345-4dd3-9664-9229852a7673)

**Comment by philschmid** [comment]
Which version of TGI are you using?

**Comment by piyushgit011** [comment]
tgi 0.8.2 
which should i use for this @philschmid ?
trained on  transformers_version = '4.28'

**Comment by philschmid** [comment]
can you please try 1.1.0 or 1.3.3

**Comment by piyushgit011** [comment]
@philschmid can this be the problem as in config.json model architecture and model type is mistral?
![image](https://github.com/philschmid/llm-sagemaker-sample/assets/96625965/9aaf283c-f6f0-4124-84aa-d0ef6c40b652)
