### ISSUE TITLE
deployment on t4 instance

### ISSUE THREAD

**Issue by piyushgit011** [philschmid/llm-sagemaker-sample#11]
hey, @philschmid how can we deploy quantized model on ml.g4dn.2xlarge?

![image](https://github.com/philschmid/llm-sagemaker-sample/assets/96625965/6ce069cc-4aeb-4c53-9f89-40f9c58dae1d)

![image](https://github.com/philschmid/llm-sagemaker-sample/assets/96625965/bd140387-5f90-437c-9f8c-0d1d279957da)
can we solve this flash attention error?

**Comment by philschmid** [comment]
You need g5 or newer
